.kokoro/psm_interop_kokoro_lib.sh

The first step of moving the source of truth of the Kokoro shared install lib to the new repo.
Source: https://github.com/grpc/grpc/blob/4f7ead2c7b7b82ad80799bbfa482184991dcd346/tools/internal_ci/linux/grpc_xds_k8s_install_test_driver.sh
New name: `.kokoro/psm_interop_kokoro_lib.sh`

Copy Kokoro shared install lib

---

framework/infrastructure/gcp/api.py
requirements.lock
requirements.txt
tests/gamma/csm_observability_test.py

- Include `google-cloud-monitoring~=2.18` into the requirements
- Add cached `GcpApiManager.monitoring_metric_service` method returning self-closing `google.cloud.monitoring_v3.MetricServiceClient`
- Add a placeholder subtest `gamma.csm_observability_test.4_check_monitoring_metric_client` that checks the monitoring API connection by making an RPC with intentionally incorrect server-validated argument, and expecting an `InvalidArgument` response from the server.

Add google-cloud-monitoring client library support

---

framework/test_cases/base_testcase.py
framework/xds_k8s_testcase.py
tests/bootstrap_generator_test.py
tests/fake_test.py

This PR:
- Make test failure messages/tracebacks unique to PSM Interop to allow for easier grepping/matchers (more details below.
- Replaces `self.id()` calls in the framework logs with custom `self.test_name`. For example,
`--- Starting subTest __main__.AppNetTest.test_ping_pong.0_create_health_check ---`
becomes
`--- Starting subTest AppNetTest.test_ping_pong.0_create_health_check ---`.
- Changes the log level of `----- TestCase ... FAILED -----` message from `info` to `error`.
- Adds `FakeTest` to make future work on the log messages easier 
The new error format:
```
E0118 09:59:38.289015 140704433060736 base_testcase.py:39] ----- PSM Test Case FAILED: ClassName.test_method -----
E0118 09:59:38.289084 140704433060736 base_testcase.py:87] ($failure_type) PSM Interop Test Failed: …
```

Make test failure messages/tracebacks unique to PSM Interop

---

framework/xds_gamma_testcase.py

When we added the active ADS check in front of the client-server connection check, but we didn't consider where GAMMA test client spends the majority of its time: `GammaXdsKubernetesTestCase.startTestClient` had `wait_for_server_channel_ready_timeout` set to 10 minutes before `wait_for_active_ads_timeout` check existed, but actual increased wait happens in `wait_for_active_ads_timeout`.
This would cause some of the CSM failures being misclassified as b/296293582 Timeout establishing ADS stream due to IAM/Workload Identity propagation delay.

Gamma tests: redistribute startTestClient wait times

---

framework/test_app/runners/k8s/gamma_server_runner.py
framework/xds_gamma_testcase.py
kubernetes-manifests/server.deployment.yaml
tests/gamma/csm_observability_test.py

This flag has been added to the client deployment but not the server deployment. Adding it to server now.
We need this fix in order for the CSM Observability Test to properly record the server side metrics.

Add --generate-mesh-id-experimental flag to server bootstrap

---

framework/test_app/runners/k8s/k8s_xds_client_runner.py
kubernetes-manifests/client.deployment.yaml
tests/gamma/csm_observability_test.py

Currently, the xds interop client is sending an empty payload for the `UnaryCall` rpc. Since testing CSM Observability will need a non-trivial payload (e.g. to verify the metrics about the number of bytes being sent), this PR will try to add 2 parameters `request_payload_size` and `response_payload_size` to the client image to control the size of the payload to be sent. Each language will need to implement this parameter in their respective client image. The one for c++ is [here](https://github.com/grpc/grpc/pull/35545).
Note that we only need to set these 2 parameters (both `request` and `resposne` payload size) on the _client deployment_ because the client will in turn tell the server how much to send back.
The good 'ol interop client already has these: …

Paramatize request/response payload size

---

framework/test_app/runners/k8s/gamma_server_runner.py

This fixes a bug with all the `GammaServerRunner` subclass not calling the super class `KubernetesBaseRunner`'s `run()` method properly, which causes the variable `self.time_start_requested` not being set and hence there is never `RunHistory` logged for the gamma server runner.
ref b/298501683

Fix bug with Gamma Server Runner not having GCP Logs link

---

tests/gamma/csm_observability_test.py

Until (and if) all changes needed for CSM Observability are backported to `v1.61.x`, we should only allow this test for the  upcoming release `v1.62.x`, and the `master` branch.

CSM Observability: update cpp version check to v1.62.x

---

framework/test_app/runners/k8s/gamma_server_runner.py
framework/test_app/runners/k8s/k8s_xds_client_runner.py
framework/xds_gamma_testcase.py
framework/xds_k8s_testcase.py
kubernetes-manifests/client.deployment.yaml
kubernetes-manifests/server.deployment.yaml
tests/gamma/csm_observability_test.py

This PR adds some assertions to test whether the metrics generated by the CSM Observability Test match what we expect.
We use the `list_time_series` cloud monitoring API to query metrics we just generated by the test run, and then verify whether the metrics data (label keys and values, and data points) is what we expected.

Add assertions to CSM Observability Test

---

framework/test_app/runners/k8s/k8s_base_runner.py

Set cursor timestamp in Logs Explorer links to the beginning. Normally the cursor points to the end, where the SIGTERM stack traces are.
Minor change. Saves a few clicks.

Set cursor timestamp in Logs Explorer links to the beginning

---

tests/gamma/csm_observability_test.py

… to place main test function near the top. Missed in #23.

Reorder CSM o11y test function order 

---

tests/gamma/csm_observability_test.py

Extends the retry conditions for `metric_client.list_time_series` call in csm_observability_test:
- Retry on HTTP 5xx + corresponding gRPC statuses. Previously only retried on 503 ServiceUnavailable.
- Retry on HTTP 429 / gRPC ResourceExhausted. The error indicates the request is rate limited, so we want to retry.
Ref [Default retry settings](https://github.com/googleapis/google-cloud-python/blob/google-cloud-monitoring-v2.18.0/packages/google-cloud-monitoring/google/cloud/monitoring_v3/services/metric_service/transports/base.py#L210-L218).

CSM O11y: improve the retry settings of list_time_series API call

---

tests/gamma/csm_observability_test.py

(minor) Remove extra newlines in o11y query helper

---

tests/gamma/csm_observability_test.py

- From a prod test failure, we observed that there may be time series data in a metric that contain no valid data points. It's unclear why they come to be at the moment
- This PR attempts to not count time series when there is no valid data point in the time series
Can't really do the filtering at the query level because the monitoring API does not support filtering by data points: https://cloud.google.com/monitoring/api/v3/filters

[CSM O11y test] Filter out time series with no valid data point

---

config/common.cfg
tests/bootstrap_generator_test.py

- Update the default bootstrap to `2bf1b5ed00f852ffea8d24759c6fa673acc9ef10`
- Add `v0.15.0`, `v0.16.0` bootstrap versions to `bootstrap_version_testcases`

update bootstrap image to v0.16.0

---

framework/test_cases/base_testcase.py
framework/xds_url_map_testcase.py
tests/fake_test.py

Result:
```
❯ ./run.sh tests/fake_test.py FakeSetupClassTest
Running tests under Python 3.9.18: /Users/sergiitk/Development/psm-interop/venv/bin/python
E0215 10:17:22.403760 140704311461824 base_testcase.py:122] ----- PSM Test Case FAILED: FakeSetupClassTest.setUpClass -----
E0215 10:17:22.403939 140704311461824 base_testcase.py:141] (ERROR) PSM Interop Test Failed: FakeSetupClassTest.setUpClass
^^^^^
[FakeSetupClassTest.setUpClass] PSM Failed Test Traceback BEGIN
File "/Users/sergiitk/Development/psm-interop/tests/fake_test.py", line 93, in setUpClass
raise OSError("Network bad!")
OSError: Network bad!
[FakeSetupClassTest.setUpClass] PSM Failed Test Traceback END
[  FAILED  ] setUpClass (__main__.FakeSetupClassTest)
```

Fix URL Map setUpClass errors not framed with `PSM Failed Test ...`

---

tests/gamma/csm_observability_test.py

We noticed a bug in CSM O11y test harness where we did not scope our metric queries to a particular test run. The fix is to add a scope on the client/server namespace which should be unique to a specific test run.

[CSM O11y] Avoid collisions between test runs when querying metrics

---

framework/test_app/runners/k8s/gamma_server_runner.py

Gamma/CSM tests: 99 percentile of tests are passing, while we see a few failures in neg status annotation propagation on the service. The dashboards do not show anything strange. Bumping the timeout to 4 mins.
Ref b/298501683, b/298501683

[Gamma] Bump the timeout for wait_service_neg_status_annotation to 4 mins

---

framework/helpers/grpc.py
framework/infrastructure/k8s.py

TIL `@functools.cached_property` allows writing to the attribute.
Allowing writes was intended in no methods in this framework.
Expected behavior always was to have lazy-loaded methods that return cached data per class instance, which is achieved with
```py
@property
@functools.cache
```
Note: Looks like `# pylint: disable=no-member` on functool methods is not needed anymore.

Replace functools.cached_property with property + functools.cache

---

.github/workflows/psm-interop.yaml
pyproject.toml
requirements-dev.txt
requirements.lock
requirements.txt

[Google Python Style Guide](https://google.github.io/styleguide/pyguide.html) has evolved, and looks all modern and futuristic now. I'll be getting tolling in this repo closer to match closer to it.
- Add [`typing-extensions`](https://typing-extensions.readthedocs.io/en/latest/) package.
- Configure isort single_line_exclusions according to https://google.github.io/styleguide/pyguide.html#2241-exemptions
With `typing-extensions`, we can use such cool things as [`TypeAlias`](https://docs.python.org/3/library/typing.html#typing.TypeAlias), [`Self`](https://docs.python.org/3/library/typing.html#typing.Self), and [`@override`](https://docs.python.org/3/library/typing.html#typing.override).
Note: we don't migrate the code to the new types yet, but we should be using these features when writing …

Style: add typing-extensions per updated Google Python Style Guide 

---

framework/bootstrap_generator_testcase.py
tests/bootstrap_generator_test.py

Same as #38, but for `BootstrapGeneratorBaseTest`.
ref b/326800953

Fix bootstrap generator setUpClass errors logs not being framed

---

framework/rpc/grpc_csds.py
framework/xds_k8s_testcase.py
framework/xds_url_map_testcase.py
tests/affinity_test.py
tests/api_listener_test.py
tests/subsetting_test.py
tests/url_map/affinity_test.py
tests/url_map/csds_test.py
tests/url_map/fault_injection_test.py
tests/url_map/header_matching_test.py
tests/url_map/metadata_filter_test.py
tests/url_map/path_matching_test.py
tests/url_map/retry_test.py
tests/url_map/timeout_test.py

Some tests incorrectly on `framework.xds_url_map_testcase` to get `DumpedXdsConfig`. This should have never been the case: csds logic and helper should be `framework.rpc.grpc_csds`.
This is especially wrong in `framework.xds_k8s_testcase` depending on `framework.xds_url_map_testcase`, while `framework.xds_url_map_testcase` depends on `framework.xds_k8s_testcase`. I'm surprised this didn't cause more problems.
This PR:
1. Moves `DumpedXdsConfig` to `framework.rpc.grpc_csds`
2. Refactors `DumpedXdsConfig` for readability
3. Addresses TODO wrt catching broad exception while parsing
4. Adds CsdsClient.fetch_client_status_parsed that returns `DumpedXdsConfig` so class users don't need to depend on json
5. Replaces all imports of `xds_url_map_testcase` that were needed just for …

Fix incorrect dependency on xds_url_map_testcase for CSDS logic

---

framework/infrastructure/k8s.py
framework/infrastructure/k8s_internal/k8s_port_forwarder.py
framework/test_app/runners/k8s/k8s_base_runner.py

Makes it more clear to what pod port forwarding started - both when starting and shutting down port forwarding.
Starting:
```
I0304 15:00:51.754341 140704470529984 k8s.py:1023] LOCAL DEV MODE: Enabling port forwarding to pod/psm-grpc-server-79cdbdddc7-w668w 10.118.1.122:8080
I0304 15:00:52.664326 140704470529984 k8s_port_forwarder.py:118] Forwarding from 127.0.0.1:61903 -> 8080
```
Shutting down:
```
I0304 15:04:21.526046 140704470529984 k8s_port_forwarder.py:126] Shutting down PortForwarder(pid='58289', namespace='sergiitk-server-20240304-2300-1db6t', destination='pod/psm-grpc-server-79cdbdddc7-w668w', '127.0.0.1:61903 -> 8080')
I0304 15:04:21.529421 140704470529984 k8s_base_runner.py:201] Port forwarders in namespace sergiitk-server-20240304-2300-1db6t stopped.
```

Improve port forwarding logging

---

framework/rpc/grpc_testing.py
framework/xds_url_map_testcase.py
tests/app_net_ssa_test.py
tests/custom_lb_test.py
tests/gamma/affinity_test.py
tests/outlier_detection_test.py
tests/url_map/affinity_test.py
tests/url_map/csds_test.py
tests/url_map/fault_injection_test.py
tests/url_map/header_matching_test.py
tests/url_map/metadata_filter_test.py
tests/url_map/path_matching_test.py
tests/url_map/retry_test.py
tests/url_map/timeout_test.py

Some tests incorrectly import `framework.xds_url_map_testcase` to get `UNARY_CALL` , `EMPTY_CALL` constants. This should have never been the case: csds logic and helper should be `framework.rpc.grpc_testing`.
This PR:
1. Moves `xds_url_map_testcase.RpcType*Call` to `grpc_testing.RPC_TYPE_*_CALL`.
2. Adds `configure_unary`, `configure_empty`, `configure_rpc_type` helpers to XdsUpdateClientConfigureServiceClient.
3. Adds `RPC_TYPES_BOTH_CALLS` constant import to simplify method calls where both call types are expected.
4. Updates all tests to import constants directly from `grpc_testing`.
Similar to https://github.com/grpc/psm-interop/pull/47.

Fix incorrect dependency on xds_url_map_testcase for client config logic

---

framework/test_app/runners/k8s/k8s_base_runner.py
kubernetes-manifests/client-secure.deployment.yaml
kubernetes-manifests/client.deployment.yaml
kubernetes-manifests/server-secure.deployment.yaml
kubernetes-manifests/server.deployment.yaml

This does two things:
1. Uses mako's TemplateLookup to improve rendering performance, and support template includes via `namespace` tag
2. In all deployment templates, aligns deployment's `containers` list with `initContainers`
Both items will be needed for the draining test #34:
1. Will use namespace tag.
2. Will make the diff much more readable because containers and initContainers already indented to the same level.

Kubernetes templating refactor

---

framework/rpc/grpc_testing.py
framework/xds_url_map_testcase.py
tests/affinity_test.py

Same as #47, #48, but for `RpcDistributionStats`.
This concludes the fix for xds_url_map_testcase dependency; after this change only url_map tests depend on it.

Fix incorrect dependency on xds_url_map_testcase for RpcDistributionStats

---

framework/helpers/grpc.py
framework/rpc/grpc_testing.py
framework/xds_k8s_testcase.py

1. Fix incorrect type hints in `_parse_rpcs_by_peer`, `_parse_rpcs_by_method`, `_parse_metadatas_by_peer`
2. Change the structure of `metadatas_by_peer` object, so that it's not repeating each header multiple times. Instead, the structure is `metadatas_by_peer[host][key] = set(unique values seen)`.
3. Parse trailing metadata. Same format as the regular one, but the key is prefixed with `TRAILING_`
```yaml
num_failures: 0
rpcs_by_peer:
psm-grpc-server-7c8bf768b6-9tq5p: 10
rpcs_by_method:
UnaryCall:
psm-grpc-server-7c8bf768b6-9tq5p: 10
metadatas_by_peer:
psm-grpc-server-7c8bf768b6-9tq5p: 'hostname: psm-grpc-server-7c8bf768b6-9tq5p, hostname:
psm-grpc-server-7c8bf768b6-9tq5p, hostname: psm-grpc-server-7c8bf768b6-9tq5p,
hostname: psm-grpc-server-7c8bf768b6-9tq5p, hostname: …
```

Improve metadatas_by_peer pretty-print

---

framework/test_app/runners/k8s/gamma_server_runner.py
framework/test_app/runners/k8s/k8s_base_runner.py
kubernetes-manifests/gamma/backend_policy.yaml
kubernetes-manifests/gamma/frontend_service.yaml
kubernetes-manifests/gamma/session_affinity_filter.yaml
kubernetes-manifests/gamma/session_affinity_policy_route.yaml
kubernetes-manifests/gamma/session_affinity_policy_service.yaml
tests/gamma/affinity_test.py

1. Fix camelCase method names and variables
2. Move SSA resource names to class  constants
3. Explicit arguments in `_create_gamma_route` and `_create_*` SSA resources
4. Add missing `owner` label to SSA manifests

Fix naming convention for gamma resources

---

tests/bootstrap_generator_test.py

Make bootstrap generator test closer to what actual users do:
1. Switch bootstrap generator docker repo from http://gcr.io/trafficdirector-prod/td-grpc-bootstrap to http://gcr.io/grpc-testing/td-grpc-bootstrap.
2. Replace commit-sha tags with version tags.
Should be a noop. All released versions are eventually published to http://gcr.io/trafficdirector-prod/td-grpc-bootstrap.

Bootstrap Generator test: use the official repo for existing images

---

framework/test_app/client_app.py

On retry errors timeout waiting for the control plane / server channel READY channel, we're not printing the traceback of the final retry attempt error; just the str(error) itself. It makes it hard to identify what exact operation failed. 
This PR changes this. New trace (before we'd see just the second part):
```
I0312 20:48:45.975962 140704686801152 client_app.py:293] [psm-grpc-client-6f998fd5d8-zjm48] ADS: Waiting for active calls to xDS control plane to trafficdirector.googleapis.com:443
File "/Users/sergiitk/Development/psm-interop/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 426, in __call__
result = fn(*args, **kwargs)
File "/Users/sergiitk/Development/psm-interop/framework/test_app/client_app.py", line 320, in …
```

Wait for xds control plane, server: preserve trace of the last error

---

framework/test_cases/base_testcase.py

1. Adds `#` before `PSM Failed Test Traceback BEGIN` and `PSM Failed Test Traceback END`. This makes the traceback look nicer when highlighted with python syntax
2. Adds another absl-formatted log statement so that in case only one test run, framed log traceback is not merged together with framework's standard output.
New format examples.
Single trace:
```py
File "/Users/sergiitk/Development/psm-interop/venv/lib/python3.9/site-packages/absl/testing/parameterized.py", line 318, in bound_param_test
return test_method(self, testcase_params)
File "/Users/sergiitk/Development/psm-interop/tests/fake_test.py", line 60, in test_true
self.assertTrue(is_true)
AssertionError: False is not true
```
Last test not merged with framework's output:
```
E0313 …
```

Minor changes to test failure error framing

---

framework/infrastructure/k8s_internal/k8s_log_collector.py
framework/test_app/runners/base_runner.py
framework/test_app/runners/k8s/k8s_base_runner.py

In the subsetting test, only the first client's log was properly collected.  The rest were virtually empty files, with only `Finished log collection for pod psm-grpc-client-..` in them.
This fixes an issue logs not being collected for subsequent calls to client/server runner's `#run()`.
The bug was in the shared log stop threading.Event being reused between different runs. So after the first run sets, log collectors for the following runs see that it's set and immediately finish collecting.

Fixes new pod log collection when runner.run() called multiple times

---

tests/subsetting_test.py

Current error message is not very suitable for buggrep:
```py
File "/tmp/work/psm-interop/tests/subsetting_test.py", line 90, in test_subsetting_basic
self.assertLen(parsed.endpoints, _SUBSET_SIZE)
AssertionError: [] has length of 0, expected 4.
```
Now it will also log `CSDS endpoint length does not match the subset size: expected=4, got=0`
ref b/328630113

(minor) subsetting_test: better error message for assertLen()

---

.kokoro/psm_interop_kokoro_lib.sh

Move CSM tests to a new regional cluster and support for regional cluster activation.
Note: the new cluster has a same name as the old one (which is allowed since it's a different cluster type): `psm-interop-csm`, region `us-central1`.
Ref b/298501683

Kokoro shared lib: Switch CSM tests to the regional cluster

---

tests/app_net_ssa_test.py
tests/gamma/affinity_session_drain_test.py

Add missing `is_supported` conditional to the AppNetSsaTest.
(plus some minor code style cleanup)
ref b/298501683
needed for cl/621686576

AppNet SSA test: add is_supported when CPP >= v1.62.x

---

framework/infrastructure/k8s.py

Sometime k8s ApiException may be constructed with `body` of type `bytes`, not `str`. When such ApiException is parsed, framework's `_handle_api_exception` fails with `TypeError: a bytes-like object is required, not 'str'`.
This PR handles this edge-case by casting `body` from `bytes` to `str`.
Trace example:
```py
File "/usr/local/google/home/ginayeh/Workspace/grpc/tools/run_tests/xds_k8s_test_driver/tests/gamma/affinity_policy_test.py", line 36, in test_ping_pong
test_servers = self.startTestServers(replica_count=REPLICA_COUNT)
File "/usr/local/google/home/ginayeh/Workspace/grpc/tools/run_tests/xds_k8s_test_driver/framework/xds_k8s_testcase.py", line 818, in startTestServers
test_servers = server_runner.run(
File …
```

Handle an edge case when k8s ApiException has body with type `bytes`

---

README.md
config/common-csm.cfg
config/common.cfg
config/local-dev.cfg.example
config/url-map.cfg
docker/psm-prestop/README.md
kubernetes-manifests/prestop-hook.yaml
tests/bootstrap_generator_test.py

Migrates PSM Interop and TD gRPC bootstrap preprod images from Container Registry (gcr.io) to Artifact Registry (pkg.dev). Container Registry deprecation notice: https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation.
Related:
- Ref b/289578176
- Bootstrap Generator: GoogleCloudPlatform/traffic-director-grpc-bootstrap#58
- Java: https://github.com/grpc/grpc-java/pull/11079
- Go: https://github.com/grpc/grpc-go/pull/7102
- CPP: https://github.com/grpc/grpc/pull/36273
- Node: https://github.com/grpc/grpc-node/pull/2712

Update PSM Interop images to Artifact Registry

---

tests/custom_lb_test.py
tests/outlier_detection_test.py

Now that https://github.com/grpc/grpc-go/issues/6288 is closed and released in v1.59.x, we can can use grpc-go xds test server directly (without overriding it with the canonical java). This affects the following tests:
- custom_lb_test
- outlier_detection_test

outlier_detection_test: don't override go server for rpc-behavior

---

framework/bootstrap_generator_testcase.py
framework/infrastructure/traffic_director.py
framework/xds_flags.py
framework/xds_k8s_testcase.py
framework/xds_url_map_test_resources.py

Flag  `--ensure_firewall` creates on-demand (per-test) firewall rule that GCP healthcheck services to request backend health status over IPv4.
This PR adds support for healtchecks over IPv6 ranges by creating another firewall rule.
https://cloud.google.com/load-balancing/docs/firewall-rules

Cover IPv6 healthcheck ranges in --ensure_firewall

---

.kokoro/psm_interop_kokoro_lib.sh
framework/infrastructure/gcp/api.py
tests/subsetting_test.py

Major rework of the shared Kokoro PSM Interop install library.
Nearly all common functionality was moved from per-language/per-branch PSM Interop build scripts to psm_interop_kokoro_lib.sh:
1. The list of tests in the each test suite 
2. Per-test-suite flag customization
3. `run_test` methods
4. `build_docker_images_if_needed` methods
5. Generic `build_test_app_docker_images` methods (simple docker build + docker push + docker tag). grpc-java is one exception, as it doesn't run docker directly, but a cloudbuild flow.
Added new options to control PSM interop test driver execution via environment variables:
```sh
readonly PSM_TESTS="${PSM_TESTS:-}"
readonly PSM_EXTRA_FLAGS="${PSM_EXTRA_FLAGS:-}"
```
Improved logging:
1. Buildscript test logs are now prepended with the date:
- when a shell …

Move all common buildscript functionality to psm_interop_kokoro_lib.sh

---

.kokoro/psm_interop_kokoro_lib.sh

Presently tests are failing due to the following error:
```
/dev/stdin: line 578: push: command not found
```
The changes were merged in #73 yesterday have a typo:  In file [.kokoro/psm_interop_kokoro_lib.sh, line 1141](https://github.com/grpc/psm-interop/pull/73/files#diff-727d543ec20c63535f31b5e8a83d9ca2762abc4349cc620a105efe9900448cedR1141), `psm::tools::run_verbose push "${image_name}:${to_tag}"` should be `psm::tools::run_verbose docker push "${image_name}:${to_tag}"`.

kokoro: Call 'docker push' correctly while pushing images

---

.kokoro/psm_interop_kokoro_lib.sh

Improves the transparency into the build scripts.
1. Reduces the number of the environment variables required to be set in per-lang buildscripts
2. Deprecate `kokoro_setup_test_driver` in favor of `psm::setup::kokoro`, more consistent with the local setup
3. Instead of implicitly sourcing `psm-interop-build-${GRPC_LANGUAGE}.sh`, have the per-lang buildscripts define `psm::lang::build_docker_images`

Shared kokoro lib: address feedback

---

.kokoro/psm_interop_kokoro_lib.sh

Minor: noticed docker build output is missing from `docker-build.log`:
- Example job log: https://btx.cloud.google.com/invocations/59f78821-adde-4484-8b03-f50e9ef2a43c/log
- `docker-build.log` for this job: https://storage.googleapis.com/grpc-testing-kokoro-prod/test_result_public/prod/grpc/node/master/xds_k8s_lb/753/20240503-100346/grpc/node/master/xds_k8s_lb/build-docker.log
Note the lines like `#5 [build 1/9] FROM docker.io/library/node:18-slim@sha256:cbfb3c9830932b7b1c2738abf47c66568fc7b06cf782d803e7ddff52b2fc835d` are missing.

(minor) Kokoro: copy stderr to build-docker.log as well

---

framework/test_app/runners/k8s/gamma_server_runner.py

We want to delete resources in the reversed creation order. 
This PR speeds up the cleanup of session affinity tests fixing the order in which `GCPBackendPolicy` and `GCPSessionAffinityFilter`/`GCPSessionAffinityPolicy` are deleted. Before this PR, this resources were deleted after `Service`, `Route`, `Deployment` they were pointing to. This resulted in extended waits of namespace (tree root) deletion.
By deleting `GCPBackendPolicy`, `GCPSessionAffinityFilter`/`GCPSessionAffinityPolicy` first, the order is fixed, and the namespace deletion op is sped up significantly.
Before - 2.5 min:
```
21:46:52 k8s_base_runner.py:913] Deleting namespace sergiitk-server-20240307-0542-6rse5
21:49:22 k8s_base_runner.py:930] Namespace sergiitk-server-20240307-0542-6rse5 deleted
```
After - 1 min:
``` …
```

Speed up CSM namespace deletion by 150%

---

framework/infrastructure/gcp/api.py
framework/infrastructure/gcp/network_services.py
framework/infrastructure/traffic_director.py

Replaces  `NetworkServicesV1Alpha1` with `NetworkServicesV1`.
Using `v1alpha1` version of network-services API to manage meshes is no longer needed. Service Routing Mesh features went GA and became available in `v1` network-services API in Q3 2022.
Notes:
1. This change only affects app_net (AKA Service Routing) tests, no other suites use network-services `v1alpha1`.
2. Security test suite uses network-services `v1beta1` (see `NetworkServicesV1Beta1` class). Security suite could probably be switched to `v1` too, but it might make sense to do this separately, and look into replacing  network-security `v1beta1` with `v1` as well.
3. After this change, Private API access key (set in `--private_api_key_secret_name`) will no longer be needed (unless we'll need to use private v1alpha1 APIs …

[AppNet] Replace NetworkServicesV1Alpha1 with NetworkServicesV1

---

framework/test_app/runners/k8s/gamma_server_runner.py
framework/test_app/runners/k8s/k8s_xds_client_runner.py

Introduces `ClientDeploymentArgs`, similar to already existing `ServerDeploymentArgs`.
Helps with decluttering `KubernetesClientRunner` class arguments. With this class, no need to create new runner arguments just to pass it to the deployment template.

Introduce `ClientDeploymentArgs`

---

.kokoro/psm_interop_kokoro_lib.sh
framework/infrastructure/gcp/compute.py
framework/infrastructure/traffic_director.py
framework/xds_k8s_testcase.py
tests/circuit_breaking_test.py

This is a port of the circuit_breaking test defined [here](https://github.com/grpc/grpc/blob/master/tools/run_tests/run_xds_tests.py#L2176). I set all clients to use the Java server because as far as I can tell, none of the others support the `keep-open` option of the `rpc-behavior` header for both `UnaryCall` and `EmptyCall`.

Add circuit_breaking test

---

config/local-dev.cfg.example
framework/infrastructure/gcp/api.py

Create a new flag `--verbose_gcp_api` that enables GCP API verbose logging (requests and responses) by setting the value of global [`googleapiclient.model.dump_request_response`](https://github.com/googleapis/google-api-python-client/blob/5a7b677757badf4324cf5bacfd17534d57500732/googleapiclient/model.py#L39). See [googleapiclient.model.BaseModel._log_request](https://github.com/googleapis/google-api-python-client/blob/5a7b677757badf4324cf5bacfd17534d57500732/googleapiclient/model.py#L108), and other `_log_request` methods in the same file.

Introduce `--verbose_gcp_api` flag to dump GCP requests and responses

---

.kokoro/psm_interop_kokoro_lib.sh
framework/infrastructure/k8s.py
framework/test_app/runners/k8s/gamma_server_runner.py
framework/test_app/runners/k8s/k8s_base_runner.py
kubernetes-manifests/gamma/route_grpc.yaml
kubernetes-manifests/gamma/route_http.yaml
kubernetes-manifests/gamma/route_http_ssafilter.yaml
tests/gamma/gamma_grpcroute_test.py

- Add support for GAMMA GRPCRoute to the framework
- And `gamma_grpcroute_test` - same sa `gamma_baseline_test`, but using GRPCRoute
Note for the reviewer: disable whitespace changes diff - most yaml changes is changing the indentation for readability.

Add GRPCRoute baseline test

---

tests/gamma/csm_observability_test.py

Enable CSM Observability tests for go >= 1.65.x.

CSM O11y: allow golang tests

---

bin/run_td_setup.py
framework/infrastructure/gcp/compute.py
framework/infrastructure/traffic_director.py
framework/test_app/runners/k8s/k8s_xds_server_runner.py
framework/xds_k8s_testcase.py
framework/xds_url_map_test_resources.py

Fixes an issue with NEG size and Backend Health waiting logic.
This bug has been in the framework from the very beginning, because we never tested the flow with (a) Regional or multizonal cluster, AND (b) a single server.
The issue: when GKE cluster has nodes in more than one zone, a NEG for the test server/service is created in each zone. If there's fewer endpoints than zones in the cluster, not every NEG will end up having a server endpoint. Therefore:
1. `wait_for_network_endpoint_group` will fail because it waits for every NEG to have more than 0 endpoints.
2. `wait_for_backends_healthy_status` will fail because NEGs with 0 endpoints will never be marked as healthy.
This PR changes the logic of:
1. `wait_for_network_endpoint_group` now waits for a NEG to merely exist in GCP APIs.
2. …

framework core: fixes a case when there are fewer endpoints than backends

---

kubernetes-manifests/client.deployment.yaml
kubernetes-manifests/server.deployment.yaml

This is needed by the Java client/server, because there's a simplistic parsing implementation. Since we need the parsing to work cross-language, we always include a value. `--secure_mode` and `--fail_on_failed_rpcs` (unused by this framework, but defined in xds-test-descriptions.md) are both boolean flags that we pass a value.

csm: Pass value to argument --enable_csm_observability

---

tests/gamma/csm_observability_test.py

Enable CSM Observability tests for Java >= 1.65.x
This is dependent on #94

CSM O11y: Enable Java

---

tests/gamma/csm_observability_test.py

Many RPCs can be buffered while waiting to connect to the server, and since the requests are now 1/4 of a MB, a lot of memory could accumulate.
Dividing the QPS by 25 and request size by 10 significantly reduces memory usage. Previously half of Java runs failed.
CC @yashykt

CSM O11y: Reduce client buffering

---

.kokoro/psm_interop_kokoro_lib.sh
framework/test_app/runners/k8s/gamma_server_runner.py
framework/test_app/runners/k8s/k8s_base_runner.py
framework/test_app/runners/k8s/k8s_xds_client_runner.py
framework/test_app/runners/k8s/k8s_xds_server_runner.py
tests/app_net_csm_observability_test.py
tests/gamma/csm_observability_test.py

- Created a new test `app_net_csm_observability_test.py` that's largely a copy of `gamma/csm_observability_test.py` with some adjustments.
- Refactor some flags to be passed to the `k8s_xds_server_runner`.
- Use `ServerDeploymentArgs` everywhere
This PR was based on top of #33, and a replacement of #72.

Add App Net based CSM Observability Test

---

tests/gamma/csm_observability_test.py

Ad-hoc run:
* Removed `otel_scope_name` and `otel_scope_version` tag for Python because python Prometheus exporter doesn't have them yet: https://github.com/open-telemetry/opentelemetry-python/issues/3072

CSM O11y: Enable Python

---

tests/app_net_csm_observability_test.py

#91, #95, #96, #97 should all be done to the AppNetCsm test as well, just that the test was merged after the fact.
Next step is to refactor out all the common logic into a Mixin class.

Catch up AppNetCsm test with latest changes

---

.kokoro/psm_interop_kokoro_lib.sh
config/common.cfg
config/url-map.cfg

Default `--server_image_canonical` updated:
- From: http://us-docker.pkg.dev/grpc-testing/psm-interop/java-server:canonical-v1.56 ([sha](http://us-docker.pkg.dev/grpc-testing/psm-interop/java-server@sha256:21124ccfb63b5c348f23102c00784f6b673b933fe03df3445497734532c82a05))
- To: http://us-docker.pkg.dev/grpc-testing/psm-interop/java-server:canonical-v1.65 
Image `java-server:canonical-v1.65` created from commit grpc/grpc-java@3c97245ae480d1afd28f9c03c12988b52b2bf6ba, branch [v1.65.x](https://github.com/grpc/grpc-java/tree/v1.65.x) - http://us-docker.pkg.dev/grpc-testing/psm-interop/java-server:3c97245ae480d1afd28f9c03c12988b52b2bf6ba ([sha](http://us-docker.pkg.dev/grpc-testing/psm-interop/java-server@sha256:3ce3f0ab808ee6f16763a2cce6ff239a1a165965b4b667f03e6c47933973048b)).
Image …

Bump server_image_canonical from java v1.56 to v1.65

---

tests/url_map/csds_test.py

A recent change to the TD gRPC bootstrap genrator adds client_default_listerner_resource_name_template to the config. This template is used to determine the LDS resource name used for LDS requests.
Our test framework currently tries to do an exact match of the LDS resource name with the dial target [here](https://github.com/grpc/psm-interop/blob/657acc2637b34ea167c5289762f02be07dae7042/tests/url_map/csds_test.py#L61)
This is the expected value now `xdstp://traffic-director-global.xds.googleapis.com/envoy.config.listener.v3.Listener/<gcp_project_number>/<vpc_network_name/mesh_id>/<dial_target>`. So the target URI is still in the new LDS but with templating around it
We can fix the assertion as below
`self.assertIn(self.hostname(), xds_config.lds["name"])`

[URL Map] Fix TestBasicCsds lds assertion as per change in TD template

---

.kokoro/psm_interop_kokoro_lib.sh
config/common-dualstack.cfg

Added dualstack test to  `psm_interop_kokoro_lib.sh`.

Add DualStack tests to psm_interop_kokoro_lib.sh

---

.kokoro/psm_interop_kokoro_lib.sh

`test_dualstack` -> `dualstack_test`

Kokoro: fix dualstack test name

---

tests/gamma/gamma_grpcroute_test.py

cc: @sergiitk 
This need not be merged in until the rollout to prod of the change begins

csm: skip grpcroute test until clusters are updated to the right state

---

.kokoro/psm_interop_kokoro_lib.sh
config/common.cfg
config/url-map.cfg

Default --server_image_canonical updated:
* From: http://us-docker.pkg.dev/grpc-testing/psm-interop/java-server:canonical-v1.65
* To: http://us-docker.pkg.dev/grpc-testing/psm-interop/java-server:canonical-v1.66
Image java-server:canonical-v1.65 created from commit https://github.com/grpc/grpc-java/commit/3c97245ae480d1afd28f9c03c12988b52b2bf6ba, branch [v1.65.x](https://github.com/grpc/grpc-java/tree/v1.65.x) - http://us-docker.pkg.dev/grpc-testing/psm-interop/java-server:3c97245ae480d1afd28f9c03c12988b52b2bf6ba ([sha](http://us-docker.pkg.dev/grpc-testing/psm-interop/java-server@sha256:3ce3f0ab808ee6f16763a2cce6ff239a1a165965b4b667f03e6c47933973048b)).
Image java-server:canonical-v1.66 created from commit https://github.com/grpc/grpc-java/commit/6043b0c166cb53104cd21a2e7f75edac09c5790122 …

Bump server_image_canonical server from java v1.65 to v1.66

---

.kokoro/psm_interop_kokoro_lib.sh

This PR fixes the syntax error caused by [this](https://github.com/grpc/psm-interop/pull/119) PR which is causing all the test runs to fail.

fixed syntax error

---

.kokoro/psm_interop_kokoro_lib.sh

Trying to address this Kokoro failure:
```
+ [21:10:41 UTC]	 Installing packages with apt, see install-apt.log
+ [21:11:21 UTC]	 Fetching GKE cluster credentials
ERROR: (gcloud.container.clusters.get-credentials) One of [--location, --zone, --region] must be supplied.
```

Add cluster for a fallback test

---

.kokoro/psm_interop_kokoro_lib.sh

This looks like the last missing piece. I was able to run test to a completion on Kokoro with this patch.
[Successful Run](https://fusion2.corp.google.com/invocations/aeee37d0-a500-4b6f-bc3e-209765139bc9/log)

Authenticate with a Docker registry

---

framework/helpers/docker.py
tests/fallback_test.py

This way we can detect when the client starts talking to an expected control plane. This makes the test more stable.
[Test run](https://fusion2.corp.google.com/ci/kokoro/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fpsm-fallback/activity/9ddb32fc-899a-404b-9c17-70ee774d736b/log)

Use channelz to determine the ADS connections state 

---

framework/infrastructure/gcp/api.py

Added an additional flag to include API key when invoking staging networkservices and networksecurity endpoints.
ref b/360284595

[compute] Add a flag to force API key parameter in v2 Discovery APIs

---

framework/helpers/docker.py
framework/helpers/xds_resources.py
tests/fallback_test.py

Python test run: https://fusion2.corp.google.com/invocations/8415611c-5b30-49ee-8688-18bd8c0e7302
Core test run: https://fusion2.corp.google.com/invocations/a9bd4699-c570-4751-9681-eb2772513711

[fallback] Use EDS cluster instead of DNS

---

.kokoro/psm_interop_kokoro_lib.sh

This PR enables some of the LB tests to run on dualstack cluster.
Logs from local run are available [here](http://fusion2/13ec7af4-f79c-4b8f-ab6f-5d9e573e960c).

Run part of LB tests on Dualstack cluster

---

tests/dualstack_test.py

v1.12.x is the next release, so that should be the first one that has the dualstack feature enabled by default.

Enable dualstack test for Node

---

.kokoro/psm_interop_kokoro_lib.sh

Reverting part of [this](https://github.com/grpc/psm-interop/pull/130) commit, as `remove_neg_test` is causing failure in dualstack test suite.

Exclude remove_neg_test from Dualstack test suite

---

.github/workflows/psm-interop.yaml
README.md
bin/pylint.sh
pyproject.toml

python3.10 is now the minimal required version (used by Kokoro tests).
Related:
- cl/370095649
- b/370095649

Drop python3.9, require python3.10 minimum

---

.kokoro/psm_interop_kokoro_lib.sh

Reverts grpc/psm-interop#133
We removed `test_remove_neg` from tests because we're seeing an issue where healthy endpoints were not present in EDS response, looks like the issue was fixed somehow, this case passed in the following manual runs:
I guess it's time for us to add back this test.

Revert "Exclude remove_neg_test from Dualstack test suite"

---

tests/gamma/gamma_grpcroute_test.py

The fix has already rolledout, we need to unskip this test. 
cc: @sergiitk

unskip gamma_grpcroute test

---

.kokoro/psm_interop_kokoro_lib.sh
config/grpc-testing.cfg
config/local-dev.cfg.example
framework/infrastructure/k8s.py
framework/xds_flags.py
framework/xds_k8s_testcase.py
kubernetes-manifests/gamma/client.deployment.yaml
kubernetes-manifests/gamma/namespace.yaml
kubernetes-manifests/gamma/route_grpc.yaml
kubernetes-manifests/gamma/server.deployment.yaml
tests/gamma/csm_observability_test.py
tests/gamma/csm_observability_test_with_injection.py

As part of CSM Gateway for Mesh GA - we have already implemented a Proxyless Bootstrap Injector in GCP which will allow clusters that are onboarded to CSM Gateway for Mesh to get the following injected into the pod with the right labels:
1. initContainer with TD Bootstrap Injector + volume Mount where the config output is generated
2. CSM O11y related labels and envvars. 
The test cluster also had to be updated to follow the new onboarding steps. I will create a CL internally to update the cluster creation script
Testing: [here](http://sponge2/659c620f-02a2-4cca-aafe-0864d2e9e2b2)

csm: modify o11y test to use proxyless bootstrap injector

---

.kokoro/psm_interop_kokoro_lib.sh

This is a small part of public preview post-launch clean up. 
Internal: b/333124034

Move app-net tests from CSM to LB suite

---

framework/xds_k8s_testcase.py
framework/xds_url_map_testcase.py

Separates `evaluate_test_config` into `parse_lang_spec_from_flags` and `evaluate_is_supported` so that custom override logic can be inserted between them.
This change exposed a bug with `cls.lang_spec.server_lang` getting out of sync with `cls.server_image` when the image is overridden in suite's `setUpClass()`.

Break up `is_supported` check into parsing and evaluating steps

---

tests/dualstack_test.py

v1.71.x is the next release, so that should be the first one that has the dualstack feature available. This change should allow running the test against master.
Local test run link (internal): http://gpaste/5061417550741504

Allow running dualstack tests for Go

---

tests/security_test.py

This requires the test implementation in https://github.com/grpc/grpc-node/pull/2909 to work. Test run:

Enable security_test for Node

---

tests/gamma/affinity_session_drain_test.py

failing stage: 04_confirm_all_servers_receive_traffic
We are verifying all 3 server receives traffic. Channel becomes ready as soon as one of the server is connected. In this case we see all RPCs going to that. We need to give time for other instances to come up.
Increasing the retry timeout from 1 min to 2 min to reduce flakiness.
Internal: b/379040924

Increased retry time for gamma.affinity_session_drain_test

---

tests/app_net_csm_observability_test.py
tests/gamma/csm_observability_test.py
tests/gamma/csm_observability_with_injection_test.py

Context in b/346828763
This should help avoid the second empty timeseries that leads to some flakiness

Fix CSM Observability tests querying

---

config/common.cfg

Update the default bootstrap from `ad35743ff01c0dc16a785e421591d7d52f3cdda4` to `ee0d85b47aad4b6352975505996116de838843ad`.
Changes: https://github.com/GoogleCloudPlatform/traffic-director-grpc-bootstrap/compare/ad35743...ee0d85b

Updating bootstrap version in common.cfg

---

framework/infrastructure/gcp/api.py

Handles operation responses that instead of setting `done: false` don't set the `done` field at all until the op is completed. 
Also allows to override the callback that determines if the op is done on per-API level.
Needed for CloudRun API: #154

GcpStandardCloudApiResource: handle non-standard operation "done"

---

framework/infrastructure/gcp/network_security.py
framework/infrastructure/gcp/network_services.py
framework/infrastructure/traffic_director.py

GcpStandardCloudApiResource._create_resource doesn't return anything, so methods returning from it had incorrect return type.
Fixing `GcpStandardCloudApiResource._create_resource` return types unraveled a few other errors, notably incorrect return types in `TrafficDirectorAppNetManager`, `GrpcRoute. from_response` and `get_http_route`.

(minor) Fix return type hints in GcpStandardCloudApiResource create_*

---

tests/dualstack_test.py

Previously, `force_namespace=True` was passed to `self.v6_server_runner.cleanup()`, but the the call to this method is conditional on `if self.v6_server_runner:`. 
Therefore, when `self.v6_server_runner` isn't set, there won't be anything to call forced namespace cleanup. In practice, I don't see this happening as the code is right now, but still fixing the code for future-proofing (f.e. bad refactoring or copy-pasting to a different code flow).

Dualstack test: fix the order of server namespace cleanup.

---

tests/authz_test.py

Passing interop test job:
This depends on https://github.com/grpc/grpc-node/pull/2945.

Enable Authz tests for Node.js

---

.kokoro/psm_interop_kokoro_lib.sh
config/common-light.cfg

The light test suite is for tests that don't use TD or GKE, and run the entire test on the same machine. Currently, the only member of the suite is the fallback test, but a federation test will be added soon.

Rename fallback test suite to light

---

framework/test_app/runners/cloud_run/cloud_run_xds_client_runner.py
framework/test_cases/cloud_run_testcase.py
tests/cloud_run_csm_inbound_test.py
tests/cloud_run_csm_outbound_test.py

Parse stats_port arg from --client_port to make sure the correct container port is used in Cloud run client for every language client.

[CloudRun to CloudRun]: Parse stats_port arg from --client_port

---

framework/xds_k8s_testcase.py

The number of failures exceeding this 1% threshold has increased recently, where most failures are just slightly off the threshold. Hence increasing the threshold should help reduce these failures.
Some examples of recently failing errors which would pass with a 2% threshold:
```
"790" unexpectedly not between "792" and "808" : Found wrong number of RPCs in flight: actual(790), expected(800 ± 1%)
"984" unexpectedly not between "990" and "1010" : Found wrong number of RPCs in flight: actual(984), expected(1000 ± 1%)
"791" unexpectedly not between "792" and "808" : Found wrong number of RPCs in flight: actual(791), expected(800 ± 1%)
```
There are also a few which would pass only with a 5% threshold.
```
"524" unexpectedly not between "495" and "505" : Found wrong number of RPCs in flight: …
```

[Circuit Breaking test] Increase RPCs in flight error threshold to 5 from 1

---

bin/cleanup/cleanup.py

The CSM cleanup script has been failing for some time with an error:
>  1. Unexpected error while deleting namespace psm-csm-server-20250715-1258-2ujy4: cleanup_gamma_server() got an unexpected keyword argument 'enable_dualstack'
[Failure run](http://sponge2/139da22a-83e8-4e92-9b85-098a5cd0b53b).
[Run with this fix](http://sponge2/bba8cc1f-fb66-4253-82f5-41654ae5f905)

cleanup: fixes gamma cleanup

---

tests/fallback_test.py

Reverts grpc/psm-interop#196
#196 broke the test with the following error:
```pytb
W0827 15:22:19.017910 128386596818944 retryers.py:175] Result check callback __main__.FallbackTest.wait_for_given_server_to_receive_rpcs.<locals>.<lambda> raised an exception.This shouldn't happen, please handle any exceptions and return return a boolean.
File "framework/helpers/retryers.py", line 173, in _check_result_wrapped
return check_result(result)
File "tests/fallback_test.py", line 347, in <lambda>
and len(stats) == 1,
TypeError: object of type 'LoadBalancerStatsResponse' has no len()
I0827 15:22:19.748453 128386497762880 docker.py:173] [server2] Shutting down
I0827 15:22:20.263980 128386506155584 docker.py:173] [server1] Shutting down
[  FAILED  ] …
```

Revert "Add retries for expected control plane statuses and rpcs"

---

framework/infrastructure/k8s.py
framework/test_app/runners/k8s/gamma_server_runner.py

Handle missing annotations and reduce timeout waiting for mesh annotation from 50 min to 20 min.

Handle missing annotations and reduce mesh annotation timeout 

---

tests/remove_neg_test.py

Failure : "assertRpcsEventuallyGoToGivenServers" was failing as sometime both the servers wind up in different priority causing the failures.
b/437342217
Fix: Restructure the test so we don't need to verify this .
Earlier flow:
1. Check if RPC are sent to S, S-alt
2. Remove neg for S-alt
3. Verify RPC are sent to S.
(We need step 1 as we want to check if RPC go to S-alt)
Changed Flow
1. Remove neg for S-alt
2.  Verify RPC are sent to S
3. Bring back neg for S-alt
4. Remove neg for S
5. Verify RPC are sent to S-alt
If we check both neg removal, we don't need to check RPC going to both S, S-alt 
prod:
Passed Run: [grpc/core/v1.71.x/branch/linux/psm-dualstack](https://source.cloud.google.com/results/invocations/8443a0a7-9964-4fb3-8de1-9b280c1140c4)

Restructure remove_neg_test
